site_name: basequark-python
repo_url: https://github.com/dq-mlnck/basequark-python
site_url: https://dq-mlnck.github.io/basequark-python
site_description: Python Application Boilerplate Template
site_author: mlnck
edit_uri: edit/main/docs/
repo_name: dq-mlnck/basequark-python
copyright: Maintained by <a href="https://dq-mlnck.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dq-mlnck/basequark-python
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/basequark-python

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
